publisher:
  ros__parameters:
    pub_frequency: 0.01
    ping_pub_topic: "ping_msg"
    ping_sub_topic: "pong_msg"
    
    msg_128B:   False
    msg_1KB":   False
    msg_10KB:   False
    msg_100KB:  True

    qos_best_effort: True
    qos_reliable: False
    qos_durability_transient_local: False
    qos_durability_volatile: True

subscriber:
  ros__parameters:
    pong_pub_topic: "pong_msg"
    pong_sub_topic: "ping_msg"

    msg_128B:   False
    msg_1KB":   False
    msg_10KB:   False
    msg_100KB:  True

    qos_best_effort: True
    qos_reliable: False
    qos_durability_transient_local: False
    qos_durability_volatile: True
